#ifndef REMOTE_LOGIC_PROFILE_H
#define REMOTE_LOGIC_PROFILE_H

#define REMOTE_LOGIC_PROFILE_CURRENT 0
#define REMOTE_LOGIC_PROFILE_ALT     1

#ifndef REMOTE_LOGIC_PROFILE
#define REMOTE_LOGIC_PROFILE REMOTE_LOGIC_PROFILE_CURRENT
#endif

#if (REMOTE_LOGIC_PROFILE != REMOTE_LOGIC_PROFILE_CURRENT) && \
    (REMOTE_LOGIC_PROFILE != REMOTE_LOGIC_PROFILE_ALT)
#error "REMOTE_LOGIC_PROFILE must be REMOTE_LOGIC_PROFILE_CURRENT or REMOTE_LOGIC_PROFILE_ALT"
#endif

#endif
	
	
	
	
	
	
	
	